[build]
  publish = "frontend/client/dist"
  command = """
    cd frontend && \
    corepack enable && \
    corepack prepare yarn@$YARN_VERSION --activate && \
    yarn cache clean && \
    yarn install --no-immutable && \
    echo "Install complete" && \
    YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn build && \
    echo "Build complete"
  """

[build.environment]
  NODE_VERSION = "22.14.0"
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "4.9.1"
  CYPRESS_INSTALL_BINARY = "0"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "1"

[[redirects]]
  from = "/api/*"
  to = "http://preview-backend.redashapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "http://preview-login.redashapp.com/login"
  status = 200

[[redirects]]
  from = "/logout"
  to = "http://preview-backend.redashapp.com/logout"
  status = 200

[[redirects]]
  from = "/status.json"
  to = "http://preview-backend.redashapp.com/status.json"
  status = 200

[[redirects]]
  from = "/static/server*"
  to = "http://preview-backend.redashapp.com/static/server:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
